### ISSUE TITLE
Major 1:  trainingSessions stats page must show line, bar graph and table

### ISSUE THREAD

**Issue by ThanhNhan2002** [Wanchester/sd-front#31]

**Comment by duyreus3105** [comment]
done with commit 457017846af489641e35adc70ecd700909d79b68

**Comment by ThanhNhan2002** [comment]
Training sessions stats is still missing line graph and table

**Comment by duyreus3105** [comment]
done
